### PR TITLE
update require in line with Rack's renaming

### LINKED ISSUE #5: Support for Rack 2
Hi!

This gem breaks when used with Rack 2, because (at the very least) the CommonLogger class moved, from `commonlogger.rb` to `common_logger.rb`.

### PR DESCRIPTION
**Pull request by anicholson**
Fixes #5.

### CODE REVIEW

**Comment by boffbowsh** [comment]
This will break for rack < 2. Could you add a conditional or a rescue and fallback please?

**Comment by anicholson** [comment]
Good idea. Done! Thanks @boffbowsh :)

**Comment by boffbowsh** [comment]
Thanks. FYI before I merge this I want to add some matrix testing to this repository so we can test the gem against rack pre- and post-2, and also against a few Ruby versions. I'll try to get to this today or tomorrow.

**Comment by boffbowsh** [comment]
Closing in favour of #7

**Pull request closed without merging**
